### ISSUE TITLE
Question about primer sequence

### ISSUE THREAD

**Issue by alienzj** [StatPhysBio/covid-bcr#7]
Dear zacmon @zacmon ,

Recently I was studying the process of B cell repertoires profiling, and I found that you provided a very good reproducible code. But when I started to reproduce it, I found that the primer files were missing (https://github.com/StatPhysBio/covid-bcr/blob/405a173dd32cdfe3e3c1f6f8b6fd2437d0b13cdf/scripts/presto_pipeline.sh#L61).

Could you help  please provide these files ? 
Thank you so much !

**Comment by zacmon** [comment]
Hi,

Thanks for sharing your feedback! The primer sequences can be found in Table S1 in the supplementary material from [our paper](https://www.sciencedirect.com/science/article/pii/S2211124721005180#app2). For ease, I've zipped the relevant primer files: [primers.zip](https://github.com/StatPhysBio/covid-bcr/files/7765613/primers.zip). Let me know if you have any other questions.

Best,
Zach

**Comment by alienzj** [comment]
Hi, zacmon,
thanks so much !
